AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HomePipeline - Spirit.com Monitor

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.11

Resources:
  HomePipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: homepipeline-checker
      CodeUri: .
      Handler: spirit_monitoring.lambda_handler
      Events:
        HourlyCheck:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: hourly-spirit-check
            Description: Check spirit.com every hour

  HomePipelineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HomePipelineFunction}
      RetentionInDays: 7

  RSMPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rsm-monitoring
      CodeUri: .
      Handler: rsm_monitoring.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 1024
      Layers:
        - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:31
      Environment:
        Variables:
          CHROME_EXECUTABLE_PATH: /opt/chrome/chrome
          CHROMEDRIVER_PATH: /opt/chromedriver
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rsm-credentials-*"
      Events:
        HourlyCheck:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: hourly-rsm-check
            Description: Check RSM portal every 5 minutes
      LoggingConfig:
        LogGroup: !Ref RSMPipelineFunctionLogGroup

  RSMPipelineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/rsm-monitoring
      RetentionInDays: 7

Outputs:
  HomePipelineFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HomePipelineFunction.Arn
  HomePipelineFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt HomePipelineFunctionRole.Arn
  RSMPipelineFunction:
    Description: "RSM Lambda Function ARN"
    Value: !GetAtt RSMPipelineFunction.Arn
  RSMPipelineFunctionIamRole:
    Description: "Implicit IAM Role created for RSM function"
    Value: !GetAtt RSMPipelineFunctionRole.Arn
