AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HomePipeline - Spirit.com Monitor

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.11

Resources:
  HomePipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: homepipeline-checker
      CodeUri: .
      Handler: spirit_monitoring.lambda_handler
      Events:
        HourlyCheck:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: hourly-spirit-check
            Description: Check spirit.com every hour

  HomePipelineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HomePipelineFunction}
      RetentionInDays: 7

  BBCPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bbc-monitoring
      CodeUri: .
      Handler: bbc_monitoring.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 128
      Events:
        HourlyCheck:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: hourly-bbc-check
            Description: Check bbc.com every hour
      LoggingConfig:
        LogGroup: !Ref BBCPipelineFunctionLogGroup

  BBCPipelineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/bbc-monitoring
      RetentionInDays: 7

Outputs:
  HomePipelineFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HomePipelineFunction.Arn
  HomePipelineFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt HomePipelineFunctionRole.Arn
  BBCPipelineFunction:
    Description: "BBC Lambda Function ARN"
    Value: !GetAtt BBCPipelineFunction.Arn
  BBCPipelineFunctionIamRole:
    Description: "Implicit IAM Role created for BBC function"
    Value: !GetAtt BBCPipelineFunctionRole.Arn
